version: '3.8'

x-image-build:
   &default-image-build
    image: ${PACKAGE}-conda
    build:
      context: ../..
      args:
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: ci/docker/build.dockerfile

x-image-check:
   &default-image-check
    image: ${PACKAGE}-check
    build:
      context: ../..
      args:
        PKG: ${PACKAGE}
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: ci/docker/check.dockerfile

x-image-test:
   &default-image-test
    image: ${PACKAGE}-test
    build:
      context: ../..
      args:
        PKG: ${PACKAGE}
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: ci/docker/test.dockerfile

x-image-run:
   &default-image-run
    image: ${PACKAGE}-run
    build:
      context: ../..
      args:
        PKG: ${PACKAGE}
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: ci/docker/run.dockerfile

x-volumes:
    &default-volumes
    volumes:
      - $PWD/..:${HOMEDIR}:ro
      - conda_build:${CONDA_BLD_PATH}
    tmpfs:
      - /var/tmpfs

services:

  conda-clean:
    image: alpine
    <<: *default-volumes
    working_dir: ${HOMEDIR}/ci
    command: make conda-clean

  conda-build:
    <<: *default-image-build
    <<: *default-volumes
    command: make conda-build

  conda-test:
    <<: *default-image-build
    <<: *default-volumes
    command: make conda-test

  conda-convert:
    <<: *default-image-build
    <<: *default-volumes
    command: make conda-convert

  conda-publish:
    <<: *default-image-build
    <<: *default-volumes
    command: make conda-publish

  flake-light:
    <<: *default-image-check
    <<: *default-volumes
    command: make flake-light

  flake:
    <<: *default-image-check
    <<: *default-volumes
    command: make flake

  bandit:
    <<: *default-image-check
    <<: *default-volumes
    command: make bandit

  check:
    <<: *default-image-check
    <<: *default-volumes
    command: make check

  pytest:
    <<: *default-image-test
    command: make test

  run:
    <<: *default-image-run

volumes:
  conda_build:
    name: ${PACKAGE}_conda_build
