name: Publish

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: [ stable ]

jobs:

  Conda:
    runs-on: ubuntu-latest

    env:
      ANACONDA_TOKEN: ${{secrets.ANACONDA_TOKEN}}
      ANACONDA_USER: ${{secrets.ANACONDA_USER}}
      ANACONDA_LABEL: main
      CONDA_BLD_PATH: /tmp/conda-bld

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: build_env
        auto-update-conda: true
        environment-file: recipe/conda_build_env.yaml
        miniconda-version: "latest"
        auto-activate-base: false

    - name: Set up output folder
      run: |
        mkdir -p ${CONDA_BLD_PATH}

    - name: Build conda package
      shell: bash -l {0}
      run: |
        conda build --no-test \
          -c brsynth \
          -c conda-forge \
          --output-folder ${CONDA_BLD_PATH} recipe

    - name: Test conda package
      shell: bash -l {0}
      run: |
        conda build --test \
          -c brsynth \
          -c conda-forge \
          ${CONDA_BLD_PATH}/*/brs_libs-*.tar.bz2

    - name: Convert to other platforms
      shell: bash -l {0}
      run: |
        conda convert \
          --platform osx-64 \
          --platform linux-64 \
          --platform win-64 \
          --output-dir ${CONDA_BLD_PATH} \
          ${CONDA_BLD_PATH}/*/brs_libs-*

    - name: Upload to anaconda
      shell: bash -l {0}
      run: |
        anaconda \
          --token ${ANACONDA_TOKEN} \
          upload \
          --user ${ANACONDA_USER} \
          --label ${ANACONDA_LABEL} \
          ${CONDA_BLD_PATH}/*/brs_libs-*.tar.bz2


# # This workflows will upload a Python Package using Twine when a release is created
# # For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
#
# name: Publish
#
# on:
#   push:
#     branches: [ stable ]
#     paths:
#       - 'RELEASE'
#
# jobs:
#
#   PyPi:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'
#     - name: Install dependencies
#       run: |
#         pip install setuptools wheel twine
#     - name: Build
#       run: |
#         python setup.py sdist bdist_wheel
#     - name: Upload
#       env:
#         TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#         TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#       run: |
#         twine upload dist/*
#
#   Conda:
#     runs-on: ubuntu-latest
#
#     strategy:
#       matrix:
#         python-version: [3.5, 3.6, 3.7]
#
#     container: docker://continuumio/anaconda3
#
#     steps:
#     - name: Waiting for module availablity on PyPi...
#       run: |
#         sleep 30
#     - name: Get module from PyPi
#       run: |
#         conda skeleton pypi brs_libs
#     - name: Customize recipe
#       run: |
#         sed -i.bck '/\ \ host\:/a \ \ \ \ - redis' brs_libs/meta.yaml
#         sed -i.bck '/\ \ run\:/a \ \ \ \ - rdkit' brs_libs/meta.yaml
#     - name: Add channels
#       run: |
#         conda config \
#           --add channels brsynth \
#           --add channels conda-forge
#     - name: Build for Python ${{ matrix.python-version }}
#       run: |
#         conda-build --python ${{ matrix.python-version }} brs_libs
#     - name: Upload package
#       env:
#         CONDA_USERNAME: ${{ secrets.CONDA_USERNAME }}
#         CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
#       run: |
#         anaconda --token ${CONDA_TOKEN} upload --user ${CONDA_USERNAME} /opt/conda/conda-bld/linux-64/*.tar.bz2
